name: GitHub Actions Demo
on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"  # toutes les minutes

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "🕒 Cron-triggered run at $(date)"
      - run: python job.py